# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Ther_mato_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ThermatoDialogBase(object):
    def setupUi(self, ThermatoDialogBase):
        ThermatoDialogBase.setObjectName("ThermatoDialogBase")
        ThermatoDialogBase.resize(496, 403)
        self.button_box = QtWidgets.QDialogButtonBox(ThermatoDialogBase)
        self.button_box.setGeometry(QtCore.QRect(140, 340, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.mFieldComboBox = QgsFieldComboBox(ThermatoDialogBase)
        self.mFieldComboBox.setGeometry(QtCore.QRect(70, 50, 160, 27))
        self.mFieldComboBox.setObjectName("mFieldComboBox")
        self.mFieldExpressionWidget = QgsFieldExpressionWidget(ThermatoDialogBase)
        self.mFieldExpressionWidget.setGeometry(QtCore.QRect(170, 100, 200, 27))
        self.mFieldExpressionWidget.setObjectName("mFieldExpressionWidget")
        self.mQgsFileWidget = QgsFileWidget(ThermatoDialogBase)
        self.mQgsFileWidget.setGeometry(QtCore.QRect(150, 190, 93, 27))
        self.mQgsFileWidget.setObjectName("mQgsFileWidget")
        self.mFontButton = QgsFontButton(ThermatoDialogBase)
        self.mFontButton.setGeometry(QtCore.QRect(60, 250, 240, 33))
        self.mFontButton.setObjectName("mFontButton")

        self.retranslateUi(ThermatoDialogBase)
        self.button_box.accepted.connect(ThermatoDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(ThermatoDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ThermatoDialogBase)

    def retranslateUi(self, ThermatoDialogBase):
        _translate = QtCore.QCoreApplication.translate
        ThermatoDialogBase.setWindowTitle(_translate("ThermatoDialogBase", "THERMATO (Thermal Risk Mapping and Analysis Tool)"))
from qgsfieldcombobox import QgsFieldComboBox
from qgsfieldexpressionwidget import QgsFieldExpressionWidget
from qgsfilewidget import QgsFileWidget
from qgsfontbutton import QgsFontButton
