# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Thermato
                                 A QGIS plugin
 This plugin analyzes the correlation between heat exposure risk, land surface
 characteristics, and socio-economic vulnerability, and provides automated
 spatial estimation of urban heat risk patterns.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-12-10
        copyright            : (C) 2026 by Prof.Dr. Albertus Deliar, S.T., M.T., Prof. Ir. Ketut Wikantika, M.Eng, Ph.D., 
                               Dr. Alfita Puspa Handayani, S.T., M.T., Hifzhan Zhafir Faza, M. Titus Gideon,
                               Prasasta Adhitya Gunawan, Muhammad Ar Rayyan Ramadhani, Rafi Dwi Nugroho
        email                : albertus.deliar@gmail.com
 ***************************************************************************/
"""
__author__    = ('Prof.Dr. Albertus Deliar, S.T., M.T., Prof. Ir. Ketut Wikantika, M.Eng, Ph.D., '
                'Dr. Alfita Puspa Handayani, S.T., M.T., Hifzhan Zhafir Faza, M. Titus Gideon,'
                'Prasasta Adhitya Gunawan, Muhammad Ar Rayyan R., Rafi Dwi Nugroho')
__date__      = '2026-06-08'
__copyright__ = ('(C) 2026 by Prof.Dr. Albertus Deliar, S.T., M.T., Prof. Ir. Ketut Wikantika, M.Eng, Ph.D.,'
                'Dr. Alfita Puspa Handayani, S.T., M.T., Hifzhan Zhafir Faza, M. Titus Gideon, '
                'Prasasta Adhitya Gunawan, Muhammad Ar Rayyan Ramadhani, Rafi Dwi Nugroho')

import os
import datetime
import tempfile
import numpy as np

from qgis.core import (
    QgsProcessingAlgorithm,
    QgsProcessingParameterRasterLayer,
    QgsProcessingParameterBoolean,
    QgsProcessingParameterMatrix,
    QgsProcessingParameterFolderDestination,
    QgsProcessingException,
    QgsProcessingOutputRasterLayer,
    QgsProcessingOutputVectorLayer,
    QgsRasterLayer,
    QgsVectorLayer,
    QgsProject,
    QgsPalettedRasterRenderer,
)
from qgis.PyQt.QtGui import QIcon
from osgeo import gdal, osr, ogr
from qgis.PyQt.QtCore import QUrl

gdal.UseExceptions()
np.seterr(all='ignore')


class ThermatoAlgorithm(QgsProcessingAlgorithm):

    # ── Parameter IDs ──
    LST_LAYER      = 'LST_LAYER'
    LST_TABLE      = 'LST_TABLE'
    NDBI_LAYER     = 'NDBI_LAYER'
    NDBI_TABLE     = 'NDBI_TABLE'
    NDVI_LAYER     = 'NDVI_LAYER'
    NDVI_TABLE     = 'NDVI_TABLE'
    POP_LAYER      = 'POP_LAYER'
    POP_TABLE      = 'POP_TABLE'
    WEIGHT_TABLE   = 'WEIGHT_TABLE'
    CLASSIFY_TABLE = 'CLASSIFY_TABLE'

    # ── Single output folder ──
    OUTPUT_FOLDER     = 'OUTPUT_FOLDER'
    OUTPUT_CONTINUOUS = 'OUTPUT_CONTINUOUS' 
    OUTPUT_CLASSIFIED = 'OUTPUT_CLASSIFIED'  
    OUTPUT_VECTOR     = 'OUTPUT_VECTOR'      
    OPEN_OUTPUT       = 'OPEN_OUTPUT'


    # ── Internal sub-folder names ──
    _RASTER_DIR = 'rasters'
    _VECTOR_DIR = 'vector'
    _REPORT_DIR = 'report'

    # ================================================================
    # Metadata
    # ================================================================
    def name(self):           return 'thermato'
    def displayName(self):    return 'THERMATO - Heat Risk Analysis'
    def group(self):          return 'THERMATO Tools'
    def groupId(self):        return 'THERMATO'
    def createInstance(self): return ThermatoAlgorithm()

    def icon(self):
        p = os.path.join(os.path.dirname(__file__), 'icon.png')
        return QIcon(p) if os.path.exists(p) else QIcon()
    
    def helpUrl(self):
        file = os.path.join(os.path.dirname(__file__), 'en.html')
        if not os.path.isfile(file):
            return ''
        return QUrl.fromLocalFile(file).toString()

    def shortHelpString(self):
        return """
        <p>Integrates <b>LST · NDBI · NDVI · Population Density</b> with
        automatic resampling and strict varification.</p>

        <p><b>⚠ LST is the reference grid and CRS.</b> All other layers are automatically 
        resampled and reprojected to match LST resolution, extent, and coordinate system. 
        LST must have a valid CRS defined — other layers with missing or different CRS 
        are handled automatically.</p>

        <h3>Single Output Folder</h3>
        <p>All outputs are saved inside <b>one folder</b> you choose:</p>
        <ul>
          <li><b>rasters/</b> – Continuous raster (Float) &amp;
              Classified raster (Byte + embedded color table)</li>
          <li><b>vector/</b>  – Classified polygon layer (GeoPackage)</li>
          <li><b>report/</b>  – HTML report, CSV, summary, rules, resampling log</li>
        </ul>

        <h3>Component Weights (MUST = 100%)</h3>
        <p>Total weight must equal exactly <b>100.0%</b> (tolerance ±0.1%).</p>

        <h3>Score Range Consistency</h3>
        <p>All components must use the same score range.</p>

        <h3>Auto-Resampling</h3>
        <p>All rasters are resampled to the LST reference grid automatically.</p>
        """

    # ================================================================
    # Parameter Definition
    # ================================================================
    def initAlgorithm(self, config=None):

        # ── LST ──
        p = QgsProcessingParameterRasterLayer(
            self.LST_LAYER, 'LST Layer (degrees C) [Reference Grid]')
        p.setHelp(
            '<b>Land Surface Temperature</b> - primary heat hazard &amp; reference grid<br>'
            'All other rasters will be resampled to match this grid.<br>'
            'Range typical: 20-50 degrees C<br>'
            'Source: Landsat 8 Band 10/11, MODIS MOD11A1<br><br>'
            '<b>Default classification:</b><br>'
            '&lt; 25 C -> Score 1 (Cool)<br>'
            '25-30 C -> Score 2 (Warm)<br>'
            '30-35 C -> Score 3 (Hot)<br>'
            '35-40 C -> Score 4 (Very Hot)<br>'
            '&gt; 40 C -> Score 5 (Extreme)'
        )
        self.addParameter(p)

        self.addParameter(QgsProcessingParameterMatrix(
            self.LST_TABLE,
            'LST Reclassification (Min C | Max C | Score)',
            numberRows=5, headers=['Min', 'Max', 'Score'],
            defaultValue=['', 25, 1.0, 25, 30, 2.0, 30, 35, 3.0, 35, 40, 4.0, 40, '', 5.0],
            optional=True
        ))

        # ── NDBI ──
        p = QgsProcessingParameterRasterLayer(self.NDBI_LAYER, 'NDBI Layer')
        p.setHelp(
            '<b>Normalized Difference Built-up Index</b> - urban sensitivity<br>'
            'Resampled to LST grid using Nearest Neighbor.<br>'
            'Range: -1 to +1 (higher = more built-up)<br>'
            'Formula: (SWIR1 - NIR) / (SWIR1 + NIR)<br><br>'
            '<b>Default classification:</b><br>'
            '&lt; -0.2 -> Score 1 (Natural)<br>'
            '-0.2 to 0.0 -> Score 2 (Mixed)<br>'
            '0.0 to 0.15 -> Score 3 (Urban)<br>'
            '0.15 to 0.3 -> Score 4 (Dense urban)<br>'
            '&gt; 0.3 -> Score 5 (Very dense)'
        )
        self.addParameter(p)

        self.addParameter(QgsProcessingParameterMatrix(
            self.NDBI_TABLE,
            'NDBI Classification (Min | Max | Score)',
            numberRows=5, headers=['Min', 'Max', 'Score'],
            defaultValue=['', -0.2, 1.0, -0.2, 0.0, 2.0,
                          0.0, 0.15, 3.0, 0.15, 0.3, 4.0, 0.3, '', 5.0],
            optional=True
        ))

        # ── NDVI ──
        p = QgsProcessingParameterRasterLayer(self.NDVI_LAYER, 'NDVI Layer')
        p.setHelp(
            '<b>Normalized Difference Vegetation Index</b> - cooling capacity<br>'
            'Resampled to LST grid using Bilinear interpolation.<br>'
            'Range: -1 to +1 (higher = more vegetation)<br>'
            'Formula: (NIR - RED) / (NIR + RED)<br>'
            '<i>Note: Classification is INVERSE - high NDVI = low risk</i><br><br>'
            '<b>Default classification:</b><br>'
            '&lt; 0.0 -> Score 5 (No vegetation)<br>'
            '0.0-0.2 -> Score 4 (Sparse)<br>'
            '0.2-0.4 -> Score 3 (Moderate)<br>'
            '0.4-0.7 -> Score 2 (Dense)<br>'
            '&gt; 0.7 -> Score 1 (Very dense, lowest risk)'
        )
        self.addParameter(p)

        self.addParameter(QgsProcessingParameterMatrix(
            self.NDVI_TABLE,
            'NDVI Classification (Min | Max | Score)',
            numberRows=5, headers=['Min', 'Max', 'Score'],
            defaultValue=['', 0.0, 5.0, 0.0, 0.2, 4.0,
                          0.2, 0.4, 3.0, 0.4, 0.7, 2.0, 0.7, '', 1.0],
            optional=True
        ))

        # ── Population ──
        p = QgsProcessingParameterRasterLayer(self.POP_LAYER, 'Population Density')
        p.setHelp(
            '<b>Population Density</b> - human exposure level<br>'
            'Resampled to LST grid using Bilinear interpolation.<br>'
            'Unit: people / km squared<br>'
            'Source: WorldPop, LandScan, GPWv4, National Census<br><br>'
            '<b>Default classification (UN-Habitat / WHO):</b><br>'
            '&lt; 100 -> Score 1 (Rural/sparse)<br>'
            '100-500 -> Score 2 (Suburban)<br>'
            '500-1500 -> Score 3 (Urban)<br>'
            '1500-5000 -> Score 4 (Dense urban)<br>'
            '&gt; 5000 -> Score 5 (Metropolitan core)'
        )
        self.addParameter(p)

        self.addParameter(QgsProcessingParameterMatrix(
            self.POP_TABLE,
            'Population Classification (Min | Max | Score)',
            numberRows=5, headers=['Min', 'Max', 'Score'],
            defaultValue=['', 100, 1.0, 100, 500, 2.0,
                          500, 1500, 3.0, 1500, 5000, 4.0, 5000, '', 5.0],
            optional=True
        ))

        # ── Weights ──
        p = QgsProcessingParameterMatrix(
            self.WEIGHT_TABLE,
            'Component Weights (MUST total 100.0%)',
            numberRows=4, headers=['Component', 'Weight (%)'],
            defaultValue=['LST', 40, 'NDBI', 20, 'NDVI', 15, 'POP', 25],
            optional=False
        )
        p.setHelp(
            '<b>STRICT VERIFICATION</b> - total must equal exactly 100.0%<br>'
            'Tolerance: +/-0.1% (99.9%-100.1% accepted)<br>'
            'No auto-normalization for transparency.<br><br>'
            '<b>Recommended ranges (literature):</b><br>'
            'LST: 40-60% (primary hazard)<br>'
            'NDBI: 15-25% (urban sensitivity)<br>'
            'NDVI: 15-30% (cooling factor)<br>'
            'POP: 5-15% (exposure)<br><br>'
            '<b>Example (matches default):</b> LST=40, NDBI=20, NDVI=15, POP=25 -> Total=100%'
        )
        self.addParameter(p)

        # ── Manual Classification Breaks ──
        p_cls = QgsProcessingParameterMatrix(
            self.CLASSIFY_TABLE,
            'Manual Classification Breaks (Min Score | Max Score | Class) [Optional]',
            numberRows=5, headers=['Min Score', 'Max Score', 'Class (1-5)'],
            defaultValue=['', 1.8, 1, 1.8, 2.6, 2, 2.6, 3.4, 3, 3.4, 4.2, 4, 4.2, '', 5],
            optional=True
        )
        p_cls.setHelp(
            '<b>Manual Classification Breaks</b> (optional)<br><br>'
            'Defines custom intervals to convert the <i>continuous</i> risk score '
            '(1.0-5.0) into discrete <i>integer classes</i> (1-5).<br><br>'
            '<b>Format per row:</b> Min Score | Max Score | Class<br>'
            'Intervals: left-inclusive, right-exclusive [Min, Max)<br>'
            'Leave Min/Max blank for -infinity / +infinity.<br><br>'
            '<b>If left empty (default):</b><br>'
            'Auto-rounding is applied - score rounded to nearest integer, clipped 1-5.<br>'
            'Suitable for most balanced datasets.<br><br>'
            '<b>Example custom breaks:</b><br>'
            '[blank]-1.8  -> Class 1 (Very Low)<br>'
            '1.8-2.6      -> Class 2 (Low)<br>'
            '2.6-3.4      -> Class 3 (Moderate)<br>'
            '3.4-4.2      -> Class 4 (High)<br>'
            '4.2-[blank]  -> Class 5 (Very High)<br><br>'
            '<b>When to use:</b> When risk distribution is skewed and you need '
            'unequal class intervals for better spatial discrimination.<br><br>'
            '<b>Color coding applied to both raster and vector outputs:</b><br>'
            'Class 1 = Green (0,128,0) - Very Low Risk<br>'
            'Class 2 = Yellow (255,220,0) - Low Risk<br>'
            'Class 3 = Orange (255,140,0) - Moderate Risk<br>'
            'Class 4 = Red (220,30,30) - High Risk<br>'
            'Class 5 = Dark Red (139,0,0) - Very High Risk'
        )
        self.addParameter(p_cls)

        # ── Single Output Folder ──
        p_out = QgsProcessingParameterFolderDestination(
            self.OUTPUT_FOLDER,
            'Output Folder (Rasters + Vector + Report)'
        )
        p_out.setHelp(
            '<b>Output Folder</b><br>'
            'Choose one folder - all results are saved inside it.<br>'
            'Sub-folders are created automatically:<br><br>'
            '<b>rasters/</b><br>'
            '&nbsp;&nbsp;risk_continuous.tif - Float32, score 1.0-5.0<br>'
            '&nbsp;&nbsp;risk_classified.tif - Byte, classes 1-5 with embedded color table<br><br>'
            '<b>vector/</b><br>'
            '&nbsp;&nbsp;risk_classified.gpkg - Polygon layer with attributes:<br>'
            '&nbsp;&nbsp;&nbsp;&nbsp;risk_class, risk_label, risk_color, area_m2, area_ha<br><br>'
            '<b>report/</b><br>'
            '&nbsp;&nbsp;report.html - Full HTML analysis report<br>'
            '&nbsp;&nbsp;high_risk_coords.csv - Class 5 pixel coordinates<br>'
            '&nbsp;&nbsp;summary.txt - Quick statistics summary<br>'
            '&nbsp;&nbsp;classification_rules.txt - Applied rules documentation<br>'
            '&nbsp;&nbsp;resampling_log.txt - Auto-resampling operations log'
        )
        self.addParameter(p_out)

        # ── Open output after running ──
        p_open = QgsProcessingParameterBoolean(
            self.OPEN_OUTPUT,
            'Open output layers in QGIS after running',
            defaultValue=True,
            optional=True
        )
        p_open.setHelp(
            '<b>Open Output in QGIS</b><br>'
            'If enabled, three layers will be automatically loaded into QGIS after processing:<br>'
            '&nbsp;&nbsp;1. <b>risk_continuous.tif</b> - Float32 continuous risk raster<br>'
            '&nbsp;&nbsp;2. <b>risk_classified.tif</b> - Classified raster with PAL color table<br>'
            '&nbsp;&nbsp;3. <b>risk_classified.gpkg</b> - Classified polygon vector layer'
        )
        self.addParameter(p_open)

        # ── Output declarations (after all parameters, per QGIS standard) ──
        self.addOutput(QgsProcessingOutputRasterLayer(
            self.OUTPUT_CONTINUOUS,
            'Continuous Risk Raster (loaded in QGIS)'
        ))
        self.addOutput(QgsProcessingOutputRasterLayer(
            self.OUTPUT_CLASSIFIED,
            'Classified Risk Raster (loaded in QGIS)'
        ))
        self.addOutput(QgsProcessingOutputVectorLayer(
            self.OUTPUT_VECTOR,
            'Classified Risk Vector (loaded in QGIS)'
        ))


    # ================================================================
    # Main Pipeline
    # ================================================================
    def processAlgorithm(self, parameters, context, feedback):
        feedback.pushInfo('=' * 70)
        feedback.pushInfo('  THERMATO - Heat Risk Analysis')
        feedback.pushInfo('  Auto-resampling | Strict verification | Single output folder')
        feedback.pushInfo('=' * 70)
        feedback.setProgress(0)

        resampled_paths = {}  # initialise early so finally block can always reference it
        try:
            # ── Extract inputs ──
            rasters = {
                'lst':  self.parameterAsRasterLayer(parameters, self.LST_LAYER,  context),
                'ndbi': self.parameterAsRasterLayer(parameters, self.NDBI_LAYER, context),
                'ndvi': self.parameterAsRasterLayer(parameters, self.NDVI_LAYER, context),
                'pop':  self.parameterAsRasterLayer(parameters, self.POP_LAYER,  context),
            }
            tables = {
                'lst':  self.parameterAsMatrix(parameters, self.LST_TABLE,  context),
                'ndbi': self.parameterAsMatrix(parameters, self.NDBI_TABLE, context),
                'ndvi': self.parameterAsMatrix(parameters, self.NDVI_TABLE, context),
                'pop':  self.parameterAsMatrix(parameters, self.POP_TABLE,  context),
            }
            weight_raw   = self.parameterAsMatrix(parameters, self.WEIGHT_TABLE,   context)
            classify_raw = self.parameterAsMatrix(parameters, self.CLASSIFY_TABLE, context)
            open_output  = self.parameterAsBoolean(parameters, self.OPEN_OUTPUT,   context)

            # ── Resolve output folder and sub-paths ──
            base_folder = self.parameterAsString(parameters, self.OUTPUT_FOLDER, context)
            raster_dir  = os.path.join(base_folder, self._RASTER_DIR)
            vector_dir  = os.path.join(base_folder, self._VECTOR_DIR)
            report_dir  = os.path.join(base_folder, self._REPORT_DIR)
            for d in (raster_dir, vector_dir, report_dir):
                os.makedirs(d, exist_ok=True)

            out_cont = os.path.join(raster_dir, 'risk_continuous.tif')
            out_cls  = os.path.join(raster_dir, 'risk_classified.tif')
            out_vec  = os.path.join(vector_dir,  'risk_classified.gpkg')

            feedback.pushInfo(f'\n  Output folder : {base_folder}')
            feedback.pushInfo(f'  Rasters       : {raster_dir}')
            feedback.pushInfo(f'  Vector        : {vector_dir}')
            feedback.pushInfo(f'  Report        : {report_dir}')

            # ── Parse & verify rules ──
            feedback.pushInfo('\n[VAL] Parsing classification tables...')
            rules = self._parse_all_tables(tables, feedback)
            feedback.setProgress(5)

            # ── Weight verification ──
            feedback.pushInfo('\n[VAL] Verifying weights (strict 100%)...')
            weights = self._verify_weights_strict(weight_raw, feedback)
            expr    = self._build_expression(weights)
            feedback.pushInfo(f'  Formula: {expr}')
            feedback.setProgress(10)

            # ── Score range consistency ──
            feedback.pushInfo('\n[VAL] Verifying score range consistency...')
            self._verify_score_consistency(rules, feedback)
            feedback.setProgress(15)

            # ── Basic raster verification ──
            feedback.pushInfo('\n[VAL] Basic raster verification + CRS audit...')
            crs_report = self._verify_raster_basics(rasters, feedback)
            feedback.setProgress(20)

            # ── Parse manual classification ──
            feedback.pushInfo('\n[VAL] Parsing manual classification table...')
            classify_rules = self._parse_classify_table(classify_raw, feedback)
            feedback.setProgress(22)

            # ── Determine class count & palette ──
            if classify_rules:
                all_cls_vals = sorted(set(c for _, _, c in classify_rules))
            else:
                all_scores = [s for rl in rules.values() for _, _, s in rl]
                max_score = int(round(max(all_scores)))
                min_score = int(round(min(all_scores)))
                all_cls_vals = list(range(min_score, max_score + 1))

            n_classes = len(all_cls_vals)
            min_cls = min(all_cls_vals)
            max_cls = max(all_cls_vals)
            cls_colors, cls_hex_colors = self._generate_class_colors(n_classes)

            actual_colors = {}
            actual_hex_colors = {}
            for idx, cv in enumerate(all_cls_vals, 1):
                actual_colors[cv] = cls_colors[idx]
                actual_hex_colors[cv] = cls_hex_colors[idx]

            feedback.pushInfo(f'  Class range: {min_cls}-{max_cls} ({n_classes} classes)')
            for cv in all_cls_vals:
                r, g, b, _ = actual_colors[cv]
                feedback.pushInfo(f'    Class {cv}: RGB({r},{g},{b}) = {actual_hex_colors[cv]}')
            feedback.setProgress(25)


            # ── [1/8] Auto-resample ──
            feedback.pushInfo('\n[1/8] Auto-resampling to reference grid (LST)...')
            if feedback.isCanceled(): raise QgsProcessingException('Cancelled by user.')
            resampled_paths, resample_log = self._auto_resample_rasters(rasters, feedback, crs_report=crs_report)
            feedback.setProgress(35)

            # ── [2/8] Read arrays ──
            feedback.pushInfo('\n[2/8] Reading resampled rasters...')
            if feedback.isCanceled(): raise QgsProcessingException('Cancelled by user.')
            lst_arr, geo = self._read_raster(resampled_paths['lst'])
            arrays = {
                'lst':  lst_arr,
                'ndbi': self._read_raster(resampled_paths['ndbi'])[0],
                'ndvi': self._read_raster(resampled_paths['ndvi'])[0],
                'pop':  self._read_raster(resampled_paths['pop'])[0],
            }
            input_stats = self._compute_input_stats(arrays)
            for k, s in input_stats.items():
                feedback.pushInfo(
                    f'  {k.upper()}: min={s["min"]:.3f}  max={s["max"]:.3f}  '
                    f'mean={s["mean"]:.3f}  coverage={s["coverage"]:.1f}%'
                )
            feedback.setProgress(50)

            # ── [3/8] Reclassify ──
            feedback.pushInfo('\n[3/8] Reclassifying...')
            if feedback.isCanceled(): raise QgsProcessingException('Cancelled by user.')
            scores = {}
            for key in arrays:
                scores[key] = self._reclass_explicit(arrays[key], rules[key], feedback)
                feedback.pushInfo(
                    f'  {key.upper()} scored: mean={np.nanmean(scores[key]):.3f}  '
                    f'range=[{np.nanmin(scores[key]):.1f}, {np.nanmax(scores[key]):.1f}]'
                )
            feedback.setProgress(60)

            # ── [4/8] Compute risk ──
            feedback.pushInfo('\n[4/8] Computing risk score...')
            if feedback.isCanceled(): raise QgsProcessingException('Cancelled by user.')
            risk_cont = self._eval_expression(expr, scores, weights, feedback)
            risk_cont = np.clip(risk_cont, 1.0, 5.0)
            feedback.pushInfo(
                f'  Risk: mean={np.nanmean(risk_cont):.3f}  '
                f'range=[{np.nanmin(risk_cont):.3f}, {np.nanmax(risk_cont):.3f}]'
            )
            feedback.setProgress(70)
            # ── [5/8] Classify (DYNAMIC) ──
            feedback.pushInfo(f'\n[5/8] Classifying to {n_classes} classes ({min_cls}-{max_cls})...')
            if feedback.isCanceled(): raise QgsProcessingException('Cancelled by user.')
            if classify_rules:
                feedback.pushInfo('  Using manual classification breaks...')
                risk_cls = self._apply_manual_classify(risk_cont, classify_rules, min_cls, max_cls, feedback)
            else:
                feedback.pushInfo('  Using auto-rounding...')
                risk_cls = self._classify_round(risk_cont, min_cls, max_cls)
            class_stats = self._risk_distribution(risk_cls, all_cls_vals, feedback)
            feedback.setProgress(78)
            
            # ── [6/8] Save rasters ──
            feedback.pushInfo('\n[6/8] Saving rasters...')
            if feedback.isCanceled(): raise QgsProcessingException('Cancelled by user.')
            self._save_raster(risk_cont, geo, out_cont, gdal.GDT_Float32, nodata=-9999.0, feedback=feedback)
            self._save_colored_classified_raster(risk_cls, geo, out_cls, actual_colors, all_cls_vals, feedback=feedback)
            feedback.setProgress(84)
            
            # ── [7/8] Save vector ──
            feedback.pushInfo('\n[7/8] Generating classified vector layer...')
            if feedback.isCanceled(): raise QgsProcessingException('Cancelled by user.')
            self._save_vector_classified(risk_cls, geo, out_cls, out_vec, actual_colors, actual_hex_colors, all_cls_vals, feedback)
            feedback.setProgress(90)

            # ── [8/8] Generate report ──
            feedback.pushInfo('\n[8/8] Generating report...')
            self._generate_report_folder(
                report_dir, input_stats, weights, expr, rules,
                risk_cont, risk_cls, class_stats, geo, resample_log,
                classify_rules, actual_hex_colors, all_cls_vals, feedback
            )
            feedback.setProgress(97)

            feedback.setProgress(100)

            # ── Open output in QGIS (optional) ──
            if open_output:
                feedback.pushInfo('\n[POST] Opening output layers in QGIS...')
                self._open_outputs_in_qgis(
                    out_cont, out_cls, out_vec,
                    actual_colors, actual_hex_colors, all_cls_vals, feedback
                )

            feedback.pushInfo('\n' + '=' * 70)
            feedback.pushInfo('  THERMATO complete!')
            feedback.pushInfo(f'  Output folder : {base_folder}')
            feedback.pushInfo(f'  Rasters       : {raster_dir}')
            feedback.pushInfo(f'  Vector        : {out_vec}')
            feedback.pushInfo(f'  Report        : {os.path.join(report_dir, "report.html")}')
            feedback.pushInfo('=' * 70)

            return {
                self.OUTPUT_FOLDER:     base_folder,
                self.OUTPUT_CONTINUOUS: out_cont,
                self.OUTPUT_CLASSIFIED: out_cls,
                self.OUTPUT_VECTOR:     out_vec,
            }

        except QgsProcessingException:
            raise
        except Exception as e:
            import traceback
            feedback.reportError(f'Error: {e}\n{traceback.format_exc()}')
            raise QgsProcessingException(str(e))
        finally:
            # Ensure temp files are always cleaned up, even on exception
            try:
                self._cleanup_temp_files(resampled_paths, feedback)
            except Exception:
                pass

    # ================================================================
    # Parse Manual Classification Table
    # ================================================================
    def _parse_classify_table(self, classify_raw, feedback):
        if not classify_raw or len(classify_raw) % 3 != 0:
            feedback.pushInfo('  No valid manual classification table - will use auto-round.')
            return []

        parsed = []
        for i in range(0, len(classify_raw), 3):
            minv = (float('-inf') if classify_raw[i]   in ('', None)
                    else float(classify_raw[i]))
            maxv = (float('inf')  if classify_raw[i+1] in ('', None)
                    else float(classify_raw[i+1]))
            try:
                cls_val = int(float(classify_raw[i+2]))
            except (ValueError, TypeError):
                raise QgsProcessingException(
                    f"[CLASSIFY ERROR] Invalid class at row {i//3+1}: "
                    f"'{classify_raw[i+2]}' - must be integer 1-5."
                )
            
            if cls_val < 1:
                raise QgsProcessingException(
                    f'[CLASSIFY ERROR] Class at row {i//3+1} = {cls_val} - must be >= 1.'
                )

            if minv >= maxv:
                raise QgsProcessingException(
                    f'[CLASSIFY ERROR] Row {i//3+1}: Min ({minv}) >= Max ({maxv}).'
                )
            parsed.append((minv, maxv, cls_val))
        all_cls_vals = sorted(set(c for _, _, c in parsed))
        feedback.pushInfo(
            f'  Manual classification: {len(parsed)} breaks, '
            f'{len(all_cls_vals)} unique classes [{min(all_cls_vals)}-{max(all_cls_vals)}]'
        )

        feedback.pushInfo(f'  Manual classification: {len(parsed)} breaks loaded.')
        for minv, maxv, cls_val in parsed:
            mns = '-inf' if minv == float('-inf') else f'{minv:.2f}'
            mxs = '+inf' if maxv == float('inf')  else f'{maxv:.2f}'
            feedback.pushInfo(f'    [{mns}, {mxs}) -> Class {cls_val}')
        return parsed 
    
    # ================================================================
    # Apply Manual Classification
    # ================================================================
    def _apply_manual_classify(self, risk_cont, classify_rules, min_cls, max_cls, feedback):
        result = np.full_like(risk_cont, np.nan, dtype=np.float32)
        for minv, maxv, cls_val in classify_rules:
            mask = (risk_cont >= minv) & (risk_cont < maxv) & ~np.isnan(risk_cont)
            result[mask] = float(cls_val)
        
        unmatched = int(np.sum(~np.isnan(risk_cont) & np.isnan(result)))
        if unmatched > 0:
            feedback.pushWarning(
                f'  {unmatched} pixels not covered by any break - set to NoData.'
            )
            # No fallback applied - unmatched pixels remain as NoData (transparent)
        
        result[np.isnan(risk_cont)] = np.nan
        return result
    
    # ================================================================
    # Open Outputs in QGIS
    # ================================================================
    def _open_outputs_in_qgis(self, out_cont, out_cls, out_vec,
                               actual_colors, actual_hex_colors, all_cls_vals, feedback):
        """
        Load continuous raster, classified raster (with PAL renderer),
        and classified vector (with categorized renderer by risk_color field)
        into the current QGIS project.
        """
        try:
            from qgis.PyQt.QtGui import QColor

            project = QgsProject.instance()

            # ── 1. Continuous raster ──
            lyr_cont = QgsRasterLayer(out_cont, 'THERMATO - Risk Continuous')
            if lyr_cont.isValid():
                project.addMapLayer(lyr_cont)
                feedback.pushInfo('  Loaded: risk_continuous.tif')
            else:
                feedback.pushWarning('  risk_continuous.tif could not be loaded in QGIS.')

            # ── 2. Classified raster with PAL palette ──
            lyr_cls = QgsRasterLayer(out_cls, 'THERMATO - Risk Classified')
            if lyr_cls.isValid():
                # Build QgsPalettedRasterRenderer classes
                pal_classes = []
                for cls_val in all_cls_vals:
                    rgba = actual_colors.get(cls_val, (128, 128, 128, 255))
                    r, g, b, a = rgba
                    pos = all_cls_vals.index(cls_val) + 1
                    ratio = pos / len(all_cls_vals)
                    if ratio <= 0.2:   lbl = 'Very Low Risk'
                    elif ratio <= 0.4: lbl = 'Low Risk'
                    elif ratio <= 0.6: lbl = 'Moderate Risk'
                    elif ratio <= 0.8: lbl = 'High Risk'
                    else:              lbl = 'Very High Risk'
                    c = QgsPalettedRasterRenderer.Class(
                        cls_val,
                        QColor(r, g, b, a),
                        f'Class {cls_val} - {lbl}'
                    )
                    pal_classes.append(c)

                renderer = QgsPalettedRasterRenderer(
                    lyr_cls.dataProvider(), 1, pal_classes
                )
                lyr_cls.setRenderer(renderer)
                lyr_cls.triggerRepaint()
                project.addMapLayer(lyr_cls)
                feedback.pushInfo(f'  Loaded: risk_classified.tif '
                                  f'({len(pal_classes)} classes with PAL renderer)')
            else:
                feedback.pushWarning('  risk_classified.tif could not be loaded in QGIS.')

            # ── 3. Classified vector with categorized renderer ──
            lyr_vec = QgsVectorLayer(out_vec, 'THERMATO - Risk Vector', 'ogr')
            if lyr_vec.isValid():
                from qgis.core import (
                    QgsCategorizedSymbolRenderer,
                    QgsRendererCategory,
                    QgsFillSymbol,
                )
                categories = []
                for cls_val in all_cls_vals:
                    hex_color = actual_hex_colors.get(cls_val, '#888888')
                    rgba = actual_colors.get(cls_val, (128, 128, 128, 255))
                    r, g, b, a = rgba

                    pos = all_cls_vals.index(cls_val) + 1
                    ratio = pos / len(all_cls_vals)
                    if ratio <= 0.2:   lbl = 'Very Low Risk'
                    elif ratio <= 0.4: lbl = 'Low Risk'
                    elif ratio <= 0.6: lbl = 'Moderate Risk'
                    elif ratio <= 0.8: lbl = 'High Risk'
                    else:              lbl = 'Very High Risk'

                    sym = QgsFillSymbol.createSimple({
                        'color': f'{r},{g},{b},{a}',
                        'outline_color': '80,80,80,255',
                        'outline_width': '0.1'
                    })
                    cat = QgsRendererCategory(
                        cls_val, sym, f'Class {cls_val} - {lbl}'
                    )
                    categories.append(cat)

                renderer_vec = QgsCategorizedSymbolRenderer('risk_class', categories)
                lyr_vec.setRenderer(renderer_vec)
                lyr_vec.triggerRepaint()
                project.addMapLayer(lyr_vec)
                feedback.pushInfo(f'  Loaded: risk_classified.gpkg '
                                  f'({len(categories)} categories)')
            else:
                feedback.pushWarning('  risk_classified.gpkg could not be loaded in QGIS.')

        except Exception as e:
            import traceback
            feedback.pushWarning(
                f'  Could not open outputs in QGIS: {e}\n{traceback.format_exc()}'
            )

    # ================================================================
    # Class Colors
    # ================================================================
    def _generate_class_colors(self, n_classes):
        """
        Generate N colors: green (class 1) -> red (class N).
        Returns: colors dict {class: (R,G,B,A)}, hex_colors dict {class: '#RRGGBB'}
        """
        colors = {}
        hex_colors = {}
        
        if n_classes == 1:
            colors[1] = (0, 255, 0, 255)
            hex_colors[1] = '#00FF00'
            return colors, hex_colors
        
        for i, cls in enumerate(range(1, n_classes + 1)):
            t = i / (n_classes - 1)  # 0.0 -> 1.0
            r = int(255 * t)
            g = int(255 * (1.0 - t))
            b = 0
            colors[cls] = (r, g, b, 255)
            hex_colors[cls] = '#{:02X}{:02X}{:02X}'.format(r, g, b)
        
        return colors, hex_colors


    # ================================================================
    # Save Colored Classified Raster
    # ================================================================
    
    def _save_colored_classified_raster(self, arr, geo, path, actual_colors, all_cls_vals, feedback=None):
        """
        Save classified raster as Byte GeoTIFF with embedded PAL color table.
        Colors are generated dynamically (green -> red gradient) based on number
        of classes. Only valid class entries are written to the color table;
        unused palette indices (beyond max class) are not set.
        NoData = 0 (transparent).
        """
        os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
        
        drv = gdal.GetDriverByName('GTiff')
        r, c = arr.shape
        
        ds = drv.Create(
            path, c, r, 1, gdal.GDT_Byte,
            options=['COMPRESS=LZW', 'TILED=YES', 'BIGTIFF=IF_NEEDED', 'PHOTOMETRIC=PALETTE']
        )
        ds.SetGeoTransform(geo['gt'])
        ds.SetProjection(geo['proj'])
        
        band = ds.GetRasterBand(1)
        band.SetNoDataValue(0)
        
        # ── Build minimal color table: only NoData(0) + valid classes ──
        # Entries beyond max(all_cls_vals) are NOT set (no 6-255 phantom bands)
        ct = gdal.ColorTable()
        
        # Entry 0 = NoData transparent
        ct.SetColorEntry(0, (0, 0, 0, 0))
        
        # Set ONLY valid class entries
        for cls_val, rgba in actual_colors.items():
            if 1 <= cls_val <= 255:
                ct.SetColorEntry(int(cls_val), rgba)
        
        # Attach color table BEFORE WriteArray (fixes PhotometricInterpretation)
        band.SetRasterColorTable(ct)
        band.SetRasterColorInterpretation(gdal.GCI_PaletteIndex)
        
        # Category names - only set for NoData and valid classes (no empty entries)
        max_cls_val = max(all_cls_vals) if all_cls_vals else 5
        cat_names = [''] * (max_cls_val + 1)
        cat_names[0] = 'NoData'
        for cls_val in all_cls_vals:
            if 1 <= cls_val <= max_cls_val:
                cat_names[cls_val] = f'Class {cls_val}'
        band.SetCategoryNames(cat_names)
        
        # ── Write pixel data (setelah color table) ──
        out = np.where(np.isnan(arr), 0, arr).astype(np.float32)
        valid_set = set(all_cls_vals)
        out_int = out.astype(np.uint8)
        
        # Zero-out pixels that are not a valid class (prevent stray values)
        invalid_mask = ~np.isin(out_int, list(valid_set)) & (out_int != 0)
        out_int[invalid_mask] = 0
        
        band.WriteArray(out_int)
        band.FlushCache()
        ds = None
        
        if feedback:
            feedback.pushInfo(f'  risk_classified.tif (Byte + PAL, {len(all_cls_vals)} classes)')

    # ================================================================
    # Save Vector Output
    # ================================================================
    def _save_vector_classified(self, risk_cls, geo, raster_path, vector_path,
                            actual_colors, actual_hex_colors, all_cls_vals, feedback):
        """
        Polygonize classified raster -> GeoPackage with risk attributes.
        Fields: risk_class, risk_label, risk_color, area_m2, area_ha.
        Colors match the PAL color table of the classified raster exactly.
        """
        src_ds = gdal.Open(raster_path)
        if src_ds is None:
            feedback.pushWarning('  Cannot open classified raster. Skipping vector.')
            return
        src_band = src_ds.GetRasterBand(1)

        ext      = os.path.splitext(vector_path)[1].lower()
        drv_name = {'.gpkg': 'GPKG', '.shp': 'ESRI Shapefile',
                    '.geojson': 'GeoJSON'}.get(ext, 'GPKG')

        ogr_drv = ogr.GetDriverByName(drv_name)
        if ogr_drv is None:
            feedback.pushWarning(f"  OGR driver '{drv_name}' unavailable. Skipping vector.")
            src_ds = None
            return

        if os.path.exists(vector_path):
            ogr_drv.DeleteDataSource(vector_path)

        os.makedirs(os.path.dirname(os.path.abspath(vector_path)), exist_ok=True)

        out_ds  = ogr_drv.CreateDataSource(vector_path)
        srs     = osr.SpatialReference()
        srs.ImportFromWkt(geo['proj'])

        layer_name = os.path.splitext(os.path.basename(vector_path))[0]
        out_layer  = out_ds.CreateLayer(layer_name, srs=srs, geom_type=ogr.wkbPolygon)

        out_layer.CreateField(ogr.FieldDefn('risk_class', ogr.OFTInteger))
        out_layer.CreateField(ogr.FieldDefn('risk_label', ogr.OFTString))
        out_layer.CreateField(ogr.FieldDefn('risk_color', ogr.OFTString))

        fld = ogr.FieldDefn('area_m2', ogr.OFTReal)
        fld.SetWidth(20); fld.SetPrecision(4)
        out_layer.CreateField(fld)

        fld = ogr.FieldDefn('area_ha', ogr.OFTReal)
        fld.SetWidth(16); fld.SetPrecision(4)
        out_layer.CreateField(fld)

        mem_drv   = ogr.GetDriverByName('Memory')
        mem_ds    = mem_drv.CreateDataSource('memdata')
        mem_layer = mem_ds.CreateLayer('tmp', srs=srs, geom_type=ogr.wkbPolygon)
        mem_layer.CreateField(ogr.FieldDefn('DN', ogr.OFTInteger))

        gdal.Polygonize(src_band, None, mem_layer, 0, [], callback=None)
        src_ds = None

        feedback.pushInfo(f'  Polygonize: {mem_layer.GetFeatureCount()} raw polygons.')

        n_classes = len(all_cls_vals)
        valid_set = set(all_cls_vals)
        
        out_layer.StartTransaction()
        enriched = 0
        skipped = 0
        
        for feat in mem_layer:
            dn = feat.GetField('DN')
            if dn is None or dn not in valid_set:
                skipped += 1
                continue
            
            geom = feat.GetGeometryRef()
            if geom is None:
                skipped += 1
                continue
            
            # Dynamic label
            if n_classes <= 5:
                label_map = {1:'Very Low Risk', 2:'Low Risk', 3:'Moderate Risk', 4:'High Risk', 5:'Very High Risk'}
                label = label_map.get(dn, f'Class {dn} Risk')
            else:
                pos = all_cls_vals.index(dn) + 1
                ratio = pos / n_classes
                if ratio <= 0.2: label = f'Class {dn} - Very Low Risk'
                elif ratio <= 0.4: label = f'Class {dn} - Low Risk'
                elif ratio <= 0.6: label = f'Class {dn} - Moderate Risk'
                elif ratio <= 0.8: label = f'Class {dn} - High Risk'
                else: label = f'Class {dn} - Very High Risk'
            
            hex_color = actual_hex_colors.get(dn, '#888888')
            
            area_m2 = geom.GetArea()
            
            nf = ogr.Feature(out_layer.GetLayerDefn())
            nf.SetGeometry(geom.Clone())
            nf.SetField('risk_class', dn)
            nf.SetField('risk_label', label)
            nf.SetField('risk_color', hex_color)
            nf.SetField('area_m2', round(area_m2, 4))
            nf.SetField('area_ha', round(area_m2 / 10000.0, 4))
            out_layer.CreateFeature(nf)
            enriched += 1
        
        out_layer.CommitTransaction()
        mem_ds = None
        out_ds = None

        feedback.pushInfo(f'  Vector: {enriched} features saved, '
                          f'{skipped} nodata/invalid skipped.')
        feedback.pushInfo('  risk_classified.gpkg')


    # ================================================================
    # Strict Weight Verification
    # ================================================================
    def _verify_weights_strict(self, weight_table, feedback):
        weights = {}

        if not weight_table or len(weight_table) % 2 != 0:
            raise QgsProcessingException(
                '[WEIGHT ERROR] Weight table empty or invalid format.\n'
                'Expected: [Component, Weight, Component, Weight, ...]'
            )

        for i in range(0, len(weight_table), 2):
            comp = str(weight_table[i]).lower().strip()
            try:
                wgt = float(weight_table[i + 1])
            except (ValueError, TypeError):
                raise QgsProcessingException(
                    f"[WEIGHT ERROR] Invalid weight for {comp}: '{weight_table[i+1]}'"
                )
            if comp not in ['lst', 'ndbi', 'ndvi', 'pop']:
                raise QgsProcessingException(
                    f"[WEIGHT ERROR] Unknown component: '{comp}' "
                    "(valid: LST, NDBI, NDVI, POP)"
                )
            if wgt < 0:
                raise QgsProcessingException(
                    f'[WEIGHT ERROR] Negative weight for {comp.upper()}: {wgt}'
                )
            weights[comp] = wgt

        missing = {'lst', 'ndbi', 'ndvi', 'pop'} - weights.keys()
        if missing:
            raise QgsProcessingException(
                f'[WEIGHT ERROR] Missing components: {[c.upper() for c in missing]}'
            )

        total = sum(weights.values())
        if not (99.9 <= total <= 100.1):
            raise QgsProcessingException(
                f'[WEIGHT ERROR] Total = {total:.2f}% - must be 100.0% (+/-0.1%)\n'
                f'  LST={weights["lst"]:.1f}  NDBI={weights["ndbi"]:.1f}  '
                f'NDVI={weights["ndvi"]:.1f}  POP={weights["pop"]:.1f}'
            )

        weights = {k: v / 100.0 for k, v in weights.items()}
        feedback.pushInfo('  Weights:')
        for comp, w in weights.items():
            feedback.pushInfo(f'    {comp.upper():5s} = {w:.3f} ({w*100:.1f}%)')
        feedback.pushInfo(f'  Total = 100.00%')
        return weights

    # ================================================================
    # Score Range Consistency Verification
    # ================================================================
    def _verify_score_consistency(self, rules, feedback):
        all_scores  = []
        comp_ranges = {}
        for comp, rule_list in rules.items():
            sc = [s for _, _, s in rule_list]
            comp_ranges[comp] = (min(sc), max(sc))
            all_scores.extend(sc)

        if not all_scores:
            raise QgsProcessingException('[SCORE ERROR] No scores found.')

        g_min, g_max = min(all_scores), max(all_scores)
        feedback.pushInfo(f'  Global score range: [{g_min}, {g_max}]')

        bad = []
        for comp, (cmin, cmax) in comp_ranges.items():
            feedback.pushInfo(f'    {comp.upper()}: [{cmin}, {cmax}]')
            if cmin < g_min or cmax > g_max:
                bad.append(f'{comp.upper()}: [{cmin}, {cmax}]')

        if bad:
            raise QgsProcessingException(
                f'[SCORE CONSISTENCY ERROR] Inconsistent ranges: {bad}\n'
                f'All components must use scores within [{g_min}, {g_max}].'
            )
        feedback.pushInfo(f'  All components consistent [{g_min}, {g_max}]')

    # ================================================================
    # Basic Raster Verification
    # ================================================================
    def _verify_raster_basics(self, rasters, feedback):
        """
        Verify all input rasters and perform full CRS audit.

        Steps:
          1. Check layer object is not None
          2. Check GDAL can open the file
          3. Check RasterCount >= 1
          4. Extract CRS from each layer
          5. Compare CRS of NDBI/NDVI/POP against LST reference
             - If undefined  -> warning, GDAL Warp will use LST CRS
             - If different  -> warning, reproject will happen in _auto_resample_rasters
             - If identical  -> info: CRS OK
          6. Check pixel coverage > 0 (no all-NoData rasters)
        Returns: dict {name: {'needs_reproject': bool, 'src_crs_wkt': str}}
        """
        # ── Step 1: None check ────────────────────────────────────────
        for name, lyr in rasters.items():
            if lyr is None:
                raise QgsProcessingException(
                    f"Layer '{name.upper()}' is invalid or not found."
                    f"Please check the input in the dialog.")
            
        # ── Step 2 + 3: GDAL open + band count ───────────────────────
        for name, lyr in rasters.items():
            ds = gdal.Open(lyr.source())
            if ds is None:
                raise QgsProcessingException(
                    f'[RASTER ERROR] Unable to open {name.upper()} — '
                    f'file may be corrupt or in an unsupported format.\n'
                    f'  Path: {lyr.source()}')
            if ds.RasterCount < 1:
                raise QgsProcessingException(
                    f'[RASTER ERROR] {name.upper()} has no raster bands.')
            ds = None

        # ── Step 4: Extract reference CRS (LST) ──────────────────────
        ref_ds  = gdal.Open(rasters['lst'].source())
        ref_wkt = ref_ds.GetProjection()
        ref_ds  = None

        ref_srs = osr.SpatialReference()
        ref_srs.ImportFromWkt(ref_wkt)
        ref_srs.SetAxisMappingStrategy(osr.OAMS_TRADITIONAL_GIS_ORDER)

        ref_crs_name = (
            ref_srs.GetAttrValue('PROJCS') or
            ref_srs.GetAttrValue('GEOGCS') or
            'Unknown CRS'
        )
        ref_epsg = ref_srs.GetAuthorityCode(None) or '?'
        feedback.pushInfo(
            f'  Reference CRS (LST): {ref_crs_name}  [EPSG:{ref_epsg}]'
        )

        if not ref_wkt:
            raise QgsProcessingException(
                '[CRS ERROR] LST layer has no CRS defined. '
                'Please assign a CRS to the LST raster before running THERMATO.'
            )

        # ── Step 5: CRS audit + coverage for each non-LST layer ──────
        crs_report = {}
        for name, lyr in rasters.items():
            if name == 'lst':
                crs_report['lst'] = {
                    'needs_reproject': False,
                    'src_crs_wkt': ref_wkt,
                    'crs_name': ref_crs_name,
                    'epsg': ref_epsg
                }
                continue

            ds      = gdal.Open(lyr.source())
            src_wkt = ds.GetProjection()

            # ── Coverage check ────────────────────────────────────────
            band     = ds.GetRasterBand(1)
            nd_val   = band.GetNoDataValue()
            arr_peek = band.ReadAsArray(
                0, 0,
                min(ds.RasterXSize, 256),
                min(ds.RasterYSize, 256)
            ).astype('float64')
            if nd_val is not None:
                arr_peek[arr_peek == nd_val] = float('nan')
            valid_cnt = int((np.isfinite(arr_peek)).sum())
            if valid_cnt == 0:
                feedback.pushWarning(
                    f'  [COVERAGE WARNING] {name.upper()}: first 256×256 sample '
                    f'contains no valid pixels — raster may be entirely NoData.'
                )
            ds = None

            # ── CRS comparison ────────────────────────────────────────
            if not src_wkt:
                feedback.pushWarning(
                    f'  [CRS WARNING] {name.upper()}: CRS is undefined. '
                    f'GDAL Warp will project it to LST CRS ({ref_crs_name}) '
                    f'during resampling.'
                )
                crs_report[name] = {
                    'needs_reproject': True,
                    'src_crs_wkt': '',
                    'crs_name': 'Undefined',
                    'epsg': '?'
                }
                continue

            src_srs = osr.SpatialReference()
            src_srs.ImportFromWkt(src_wkt)
            src_srs.SetAxisMappingStrategy(osr.OAMS_TRADITIONAL_GIS_ORDER)

            src_crs_name = (
                src_srs.GetAttrValue('PROJCS') or
                src_srs.GetAttrValue('GEOGCS') or
                'Unknown CRS'
            )
            src_epsg = src_srs.GetAuthorityCode(None) or '?'

            # IsSame() returns 1 if CRS are equivalent
            same_crs = bool(src_srs.IsSame(ref_srs))

            if same_crs:
                feedback.pushInfo(
                    f'  [CRS OK]   {name.upper()}: {src_crs_name} '
                    f'[EPSG:{src_epsg}] — matches reference'
                )
                crs_report[name] = {
                    'needs_reproject': False,
                    'src_crs_wkt': src_wkt,
                    'crs_name': src_crs_name,
                    'epsg': src_epsg
                }
            else:
                feedback.pushWarning(
                    f'  [CRS MISMATCH] {name.upper()}: '
                    f'{src_crs_name} [EPSG:{src_epsg}]  ≠  '
                    f'{ref_crs_name} [EPSG:{ref_epsg}]\n'
                    f'    → Will be reprojected to {ref_crs_name} '
                    f'during resampling step.'
                )
                crs_report[name] = {
                    'needs_reproject': True,
                    'src_crs_wkt': src_wkt,
                    'crs_name': src_crs_name,
                    'epsg': src_epsg
                }

        # ── Summary ───────────────────────────────────────────────────
        n_mismatch = sum(1 for v in crs_report.values() if v['needs_reproject'])
        if n_mismatch:
            feedback.pushWarning(
                f'  [CRS SUMMARY] {n_mismatch} layer(s) have different CRS '
                f'and will be reprojected automatically.'
            )
        else:
            feedback.pushInfo('  [CRS SUMMARY] All layers share the same CRS — OK')

        feedback.pushInfo('  Basic verification passed')
        return crs_report
    # ================================================================
    # Auto-Resampling Pipeline
    # ================================================================
    def _auto_resample_rasters(self, rasters, feedback, crs_report=None):
        """
        Resample all input rasters to the LST reference grid.
        If a layer has a different CRS (detected in _verify_raster_basics),
        GDAL Warp automatically reprojects it to the LST CRS in the same step.
        Resampling method per component:
          NDBI -> Nearest Neighbor  (discrete index, no interpolation)
          NDVI -> Bilinear          (smooth gradient)
          POP  -> Bilinear          (smooth gradient)
        """
        import shutil
        if crs_report is None:
            crs_report = {}

        ref_path = rasters['lst'].source()
        temp_dir = tempfile.mkdtemp(prefix='thermato_')
        resampled_paths = {'lst': ref_path}
        resample_log    = []

        ref_ds   = gdal.Open(ref_path)
        ref_gt   = ref_ds.GetGeoTransform()
        ref_proj = ref_ds.GetProjection()
        ref_rows = ref_ds.RasterYSize
        ref_cols = ref_ds.RasterXSize
        ref_ds   = None

        ref_srs = osr.SpatialReference()
        ref_srs.ImportFromWkt(ref_proj)
        ref_crs_name = (
            ref_srs.GetAttrValue('PROJCS') or
            ref_srs.GetAttrValue('GEOGCS') or 'Unknown'
        )

        feedback.pushInfo(
            f'  Reference (LST): {ref_rows}x{ref_cols}, '
            f'res={abs(ref_gt[1]):.6f}x{abs(ref_gt[5]):.6f}  '
            f'CRS: {ref_crs_name}'
        )
        resample_log.append(f'Reference Grid (LST): {ref_rows}x{ref_cols} pixels')
        resample_log.append(f'  Resolution : {abs(ref_gt[1]):.6f} x {abs(ref_gt[5]):.6f}')
        resample_log.append(f'  CRS        : {ref_crs_name}')
        resample_log.append(
            f'  Extent     : [{ref_gt[0]:.4f}, '
            f'{ref_gt[3] + ref_rows*ref_gt[5]:.4f}, '
            f'{ref_gt[0] + ref_cols*ref_gt[1]:.4f}, '
            f'{ref_gt[3]:.4f}]'
        )
        resample_log.append('')

        methods = {
            'ndbi': (gdal.GRA_NearestNeighbour, 'Nearest Neighbor'),
            'ndvi': (gdal.GRA_Bilinear,         'Bilinear'),
            'pop':  (gdal.GRA_Bilinear,         'Bilinear'),
        }

        for name, lyr in rasters.items():
            if name == 'lst':
                continue

            input_path  = lyr.source()
            output_path = os.path.join(temp_dir, f'{name}_resampled.tif')
            method, method_name = methods[name]

            # Determine if CRS reproject is needed
            info     = crs_report.get(name, {})
            needs_rp = info.get('needs_reproject', False)
            src_crs  = info.get('crs_name', 'Unknown')
            src_epsg = info.get('epsg', '?')

            src_ds   = gdal.Open(input_path)
            src_gt   = src_ds.GetGeoTransform()
            src_rows = src_ds.RasterYSize
            src_cols = src_ds.RasterXSize
            src_ds   = None

            # Grid is identical AND no reproject needed -> simple copy
            grid_same = (
                abs(abs(src_gt[1]) - abs(ref_gt[1])) < 1e-6 and
                abs(abs(src_gt[5]) - abs(ref_gt[5])) < 1e-6 and
                abs(src_gt[0]      - ref_gt[0])       < 1e-6 and
                abs(src_gt[3]      - ref_gt[3])        < 1e-6 and
                src_rows == ref_rows and src_cols == ref_cols
            )

            if grid_same and not needs_rp:
                feedback.pushInfo(
                    f'  {name.upper()}: grid identical, CRS matches — copying...'
                )
                shutil.copy2(input_path, output_path)
                resample_log.append(f'{name.upper()}: No resampling needed (grid + CRS identical)')
            else:
                action_parts = []
                if needs_rp:
                    action_parts.append(
                        f'reproject {src_crs} [EPSG:{src_epsg}] → {ref_crs_name}'
                    )
                if not grid_same:
                    action_parts.append(
                        f'resample {src_rows}x{src_cols} → {ref_rows}x{ref_cols} ({method_name})'
                    )
                action_str = ' + '.join(action_parts)
                feedback.pushInfo(f'  {name.upper()}: {action_str}')

                wo = gdal.WarpOptions(
                    format='GTiff',
                    width=ref_cols,
                    height=ref_rows,
                    outputBounds=[
                        ref_gt[0],
                        ref_gt[3] + ref_rows * ref_gt[5],
                        ref_gt[0] + ref_cols * ref_gt[1],
                        ref_gt[3],
                    ],
                    dstSRS=ref_proj,         # always set: reprojects if CRS differs
                    resampleAlg=method,
                    creationOptions=['COMPRESS=LZW', 'TILED=YES']
                )
                res = gdal.Warp(output_path, input_path, options=wo)
                if res is None:
                    raise QgsProcessingException(
                        f'[WARP ERROR] Failed to resample/reproject {name.upper()}. '
                        f'Check that the file is not corrupt and the CRS is readable.'
                    )
                res = None

                log_line = f'{name.upper()}: {action_str}'
                if needs_rp:
                    log_line += f'\n  Source CRS : {src_crs} [EPSG:{src_epsg}]'
                    log_line += f'\n  Target CRS : {ref_crs_name}'
                resample_log.append(log_line)

            resampled_paths[name] = output_path
            resample_log.append('')

        feedback.pushInfo('  Auto-resampling + reprojection complete')
        return resampled_paths, resample_log

    # ================================================================
    # Classification Tables
    # ================================================================
    def _parse_all_tables(self, tables, feedback):
        defaults = {
            'lst':  [(float('-inf'), 25,  1.0), (25,  30,  2.0), (30,  35,          3.0),
                     (35,           40,  4.0), (40,  float('inf'), 5.0)],
            'ndbi': [(float('-inf'), -0.2, 1.0), (-0.2, 0.0, 2.0), (0.0,  0.15,      3.0),
                     (0.15,         0.3,  4.0), (0.3,  float('inf'), 5.0)],
            'ndvi': [(float('-inf'), 0.0,  5.0), (0.0,  0.2,  4.0), (0.2,  0.4,       3.0),
                     (0.4,          0.7,  2.0), (0.7,  float('inf'), 1.0)],
            'pop':  [(float('-inf'), 100,  1.0), (100,  500,  2.0), (500,  1500,       3.0),
                     (1500,         5000, 4.0), (5000, float('inf'), 5.0)],
        }
        rules = {}
        for key, table in tables.items():
            if table and len(table) % 3 == 0:
                parsed = []
                for i in range(0, len(table), 3):
                    minv = (float('-inf') if table[i]   in ('', None) else float(table[i]))
                    maxv = (float('inf')  if table[i+1] in ('', None) else float(table[i+1]))
                    valv = float(table[i+2])
                    if minv >= maxv:
                        raise QgsProcessingException(
                            f'[TABLE ERROR] {key.upper()} row {i//3+1}: '
                            f'Min ({minv}) >= Max ({maxv})'
                        )
                    parsed.append((minv, maxv, valv))
                rules[key] = parsed
                feedback.pushInfo(f'  {key.upper()}: {len(parsed)} custom classes')
            else:
                rules[key] = defaults[key]
                feedback.pushInfo(f'  {key.upper()}: default classes')
        return rules

    def _reclass_explicit(self, arr, rules, feedback):
        scores = np.full_like(arr, np.nan, dtype=np.float64)
        for minv, maxv, val in rules:
            scores[(arr >= minv) & (arr < maxv)] = val
        unmatched = np.sum(~np.isnan(arr) & np.isnan(scores))
        if unmatched > 0:
            feedback.pushWarning(f'    {unmatched} pixels unmatched -> NaN')
        return scores

    # ================================================================
    # Expression Building & Evaluation
    # ================================================================
    def _build_expression(self, weights):
        return (
            f"LST x{weights['lst']:.3f} + NDBI x{weights['ndbi']:.3f} + "
            f"NDVI x{weights['ndvi']:.3f} + POP x{weights['pop']:.3f}"
        )

    def _eval_expression(self, expr, scores, weights, feedback):
        try:
            risk = (scores['lst']  * weights['lst']  +
                    scores['ndbi'] * weights['ndbi'] +
                    scores['ndvi'] * weights['ndvi'] +
                    scores['pop']  * weights['pop'])
        except Exception as e:
            raise QgsProcessingException(f'[COMPUTATION ERROR] {e}')
        if not isinstance(risk, np.ndarray):
            raise QgsProcessingException('Expression must return an array.')
        return risk.astype(np.float64)

    # ================================================================
    # Classification & Statistics
    # ================================================================
    def _classify_round(self, risk_cont, min_cls, max_cls):
        rounded = np.round(risk_cont).astype(np.float32)
        rounded = np.clip(rounded, min_cls, max_cls)
        rounded[np.isnan(risk_cont)] = np.nan
        return rounded

    def _risk_distribution(self, risk_cls, all_cls_vals, feedback):
        valid = risk_cls[~np.isnan(risk_cls)].astype(int)
        if valid.size == 0:
            feedback.pushWarning('  No valid pixels.')
            return {}
        u, c = np.unique(valid, return_counts=True)
        total = c.sum()
        stats = {}
        n_cls = len(all_cls_vals)
        
        for cls, cnt in zip(u, c):
            stats[cls] = int(cnt)
            if cls in all_cls_vals:
                pos = all_cls_vals.index(cls) + 1
                ratio = pos / n_cls
                if ratio <= 0.2: lbl = 'Very Low'
                elif ratio <= 0.4: lbl = 'Low'
                elif ratio <= 0.6: lbl = 'Moderate'
                elif ratio <= 0.8: lbl = 'High'
                else: lbl = 'Very High'
            else:
                lbl = '?'
            feedback.pushInfo(f'  Class {cls} ({lbl:10s}): {100*cnt/total:5.1f}% ({cnt:,} px)')
        return stats


    # ================================================================
    # I/O Operations
    # ================================================================
    def _save_raster(self, arr, geo, path, dtype, nodata, feedback):
        os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
        drv  = gdal.GetDriverByName('GTiff')
        r, c = arr.shape
        ds   = drv.Create(path, c, r, 1, dtype,
                          options=['COMPRESS=LZW', 'TILED=YES', 'BIGTIFF=IF_NEEDED'])
        ds.SetGeoTransform(geo['gt'])
        ds.SetProjection(geo['proj'])
        band = ds.GetRasterBand(1)
        out  = np.where(np.isnan(arr), nodata, arr)
        band.WriteArray(out.astype(np.int16 if dtype == gdal.GDT_Int16 else np.float32))
        band.SetNoDataValue(float(nodata))
        band.FlushCache()
        ds = None
        if feedback:
            feedback.pushInfo(f'  {os.path.basename(path)}')

    def _read_raster(self, path):
        ds = gdal.Open(path)
        if ds is None:
            raise QgsProcessingException(f'Cannot open: {path}')
        band   = ds.GetRasterBand(1)
        arr    = band.ReadAsArray().astype(np.float64)
        nodata = band.GetNoDataValue()
        if nodata is not None:
            arr[arr == nodata] = np.nan
        geo = {'gt': ds.GetGeoTransform(), 'proj': ds.GetProjection(),
               'shape': arr.shape}
        ds = None
        return arr, geo

    def _compute_input_stats(self, arrays):
        stats = {}
        for key, arr in arrays.items():
            v = arr[~np.isnan(arr)]
            stats[key] = {
                'min':      float(np.min(v))  if v.size else float('nan'),
                'max':      float(np.max(v))  if v.size else float('nan'),
                'mean':     float(np.mean(v)) if v.size else float('nan'),
                'std':      float(np.std(v))  if v.size else float('nan'),
                'valid_px': int(v.size),
                'total_px': int(arr.size),
                'coverage': float(v.size / arr.size * 100) if arr.size > 0 else 0.0,
            }
        return stats

    # ================================================================
    # Report Generation
    # ================================================================
    def _generate_report_folder(self, folder_path, input_stats, weights, expr, rules,
                            risk_cont, risk_cls, class_stats, geo, resample_log,
                            classify_rules, actual_hex_colors, all_cls_vals, feedback):
        os.makedirs(folder_path, exist_ok=True)
        
        html = self._build_html_report(
            input_stats, weights, expr, rules, risk_cont, risk_cls,
            class_stats, geo, resample_log, classify_rules,
            actual_hex_colors, all_cls_vals
        )
        with open(os.path.join(folder_path, 'report.html'), 'w', encoding='utf-8') as f:
            f.write(html)
        feedback.pushInfo('  report.html')

        max_cls_val = max(all_cls_vals)
        csv_txt = self._build_csv_coords(risk_cls, risk_cont, geo, max_cls_val)
        with open(os.path.join(folder_path, 'high_risk_coords.csv'), 'w', encoding='utf-8') as f:
            f.write(csv_txt)
        feedback.pushInfo('  high_risk_coords.csv')

        summ = self._build_summary_text(
            input_stats, weights, expr, class_stats, risk_cont,
            all_cls_vals, actual_hex_colors
        )
        with open(os.path.join(folder_path, 'summary.txt'), 'w', encoding='utf-8') as f:
            f.write(summ)
        feedback.pushInfo('  summary.txt')

        rules_txt = self._build_rules_text(rules)
        with open(os.path.join(folder_path, 'classification_rules.txt'), 'w', encoding='utf-8') as f:
            f.write(rules_txt)
        feedback.pushInfo('  classification_rules.txt')

        with open(os.path.join(folder_path, 'resampling_log.txt'), 'w', encoding='utf-8') as f:
            f.write('THERMATO - Auto-Resampling Log\n')
            f.write(f'Generated: {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}\n\n')
            f.write('\n'.join(resample_log))
        feedback.pushInfo('  resampling_log.txt')

    
    def _build_html_report(self, input_stats, weights, expr, rules, risk_cont, risk_cls,
                       class_stats, geo, resample_log, classify_rules,
                       actual_hex_colors, all_cls_vals):
        
        valid_risk  = risk_cont[~np.isnan(risk_cont)]
        r_mean = float(np.mean(valid_risk))
        r_min  = float(np.min(valid_risk))
        r_max  = float(np.max(valid_risk))
        r_std  = float(np.std(valid_risk))

        total_valid = sum(class_stats.values())
        max_cls = max(all_cls_vals)
        hr_count = class_stats.get(max_cls, 0)

        hr_pct      = 100 * hr_count / total_valid if total_valid else 0

        gt = geo['gt']
        ts = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')

        n_cls = len(all_cls_vals)

        cls_rows = ''
        for cls in all_cls_vals:  # ← loop all_cls_vals bukan 1-5
            cnt = class_stats.get(cls, 0)
            pct = 100 * cnt / total_valid if total_valid else 0
            bar = '█' * int(pct / 2)
            hex_color = actual_hex_colors.get(cls, '#888888')
            
            pos = all_cls_vals.index(cls) + 1
            ratio = pos / n_cls
            if ratio <= 0.2: lbl = 'Very Low'
            elif ratio <= 0.4: lbl = 'Low'
            elif ratio <= 0.6: lbl = 'Moderate'
            elif ratio <= 0.8: lbl = 'High'
            else: lbl = 'Very High'
            
            cls_rows += (
                f"<tr>"
                f"<td><span style='display:inline-block;width:14px;height:14px;"
                f"background:{hex_color};border-radius:3px;margin-right:6px'></span>"
                f"<b>{cls}</b></td>"
                f"<td>{lbl}</td>"
                f"<td style='text-align:right'>{cnt:,}</td>"
                f"<td style='text-align:right'>{pct:.1f}%</td>"
                f"<td style='font-family:monospace;color:#6f42c1'>{bar}</td></tr>\n"
            )

        stat_rows = ''
        for key, s in input_stats.items():
            stat_rows += (
                f"<tr><td><b>{key.upper()}</b></td>"
                f"<td>{s['min']:.3f}</td><td>{s['max']:.3f}</td>"
                f"<td>{s['mean']:.3f}</td><td>{s['std']:.3f}</td>"
                f"<td>{s['coverage']:.1f}%</td></tr>\n"
            )

        rules_html = ''
        rnames = {'lst':'LST Temperature','ndbi':'NDBI Built-up',
                  'ndvi':'NDVI Vegetation','pop':'Population Density'}
        for key, rl in rules.items():
            rules_html += f"<h4>{rnames[key]}</h4>"
            rules_html += "<table><tr><th>Min</th><th>Max</th><th>Score</th></tr>"
            for mn, mx, vl in rl:
                mns = '-inf' if mn == float('-inf') else f'{mn:.2f}'
                mxs = '+inf' if mx == float('inf')  else f'{mx:.2f}'
                rules_html += (f"<tr><td>{mns}</td><td>{mxs}</td>"
                               f"<td><b>{vl:.1f}</b></td></tr>")
            rules_html += '</table>'

        if classify_rules:
            classify_html = '<h2>Manual Classification Breaks (Applied)</h2>'
            classify_html += ('<table><tr><th>Min Score</th><th>Max Score</th>'
                              '<th>Class</th><th>Label</th></tr>')
            all_cls_in_rules = sorted(set(c for _, _, c in classify_rules))
            n_cls_rules = len(all_cls_in_rules)
            for minv, maxv, cls_val in classify_rules:
                mns = '-inf' if minv == float('-inf') else f'{minv:.2f}'
                mxs = '+inf' if maxv == float('inf')  else f'{maxv:.2f}'
                pos = all_cls_in_rules.index(cls_val) + 1 if cls_val in all_cls_in_rules else 1
                ratio = pos / max(n_cls_rules, 1)
                if ratio <= 0.2:   dyn_lbl = 'Very Low'
                elif ratio <= 0.4: dyn_lbl = 'Low'
                elif ratio <= 0.6: dyn_lbl = 'Moderate'
                elif ratio <= 0.8: dyn_lbl = 'High'
                else:              dyn_lbl = 'Very High'
                classify_html += (f"<tr><td>{mns}</td><td>{mxs}</td>"
                                  f"<td><b>{cls_val}</b></td>"
                                  f"<td>{dyn_lbl}</td></tr>")
            classify_html += '</table>'
        else:
            classify_html = ('<h2>Classification Method</h2>'
                             '<p>Auto-rounding used. Score rounded to nearest '
                             'integer, clipped to [1-5].</p>')

        alert_html = ''
        max_cls_lbl = max_cls
        if hr_pct > 20:
            alert_html = (f'<div class="alert danger"><b>More than 20% Very High '
                          f'Risk (Class {max_cls_lbl}).</b> Immediate mitigation recommended.</div>')
        elif hr_pct > 10:
            alert_html = (f'<div class="alert warning"><b>More than 10% Very High '
                          f'Risk (Class {max_cls_lbl}).</b> Consider mitigation strategies.</div>')

        resample_html = ('<div class="code">' +
                         '<br>'.join(resample_log[:10]) + '</div>')
        if len(resample_log) > 10:
            resample_html += '<p><i>See resampling_log.txt for complete details.</i></p>'

        legend_html = "<div style='display:flex;gap:12px;flex-wrap:wrap;margin:12px 0'>"
        for cls in all_cls_vals:
            hex_color = actual_hex_colors[cls]
            pos = all_cls_vals.index(cls) + 1
            ratio = pos / n_cls
            if ratio <= 0.2: lbl = 'Very Low'
            elif ratio <= 0.4: lbl = 'Low'
            elif ratio <= 0.6: lbl = 'Moderate'
            elif ratio <= 0.8: lbl = 'High'
            else: lbl = 'Very High'
            
            legend_html += (
                f"<div style='display:flex;align-items:center;gap:6px'>"
                f"<div style='width:20px;height:20px;background:{hex_color};"
                f"border-radius:4px;border:1px solid #ccc'></div>"
                f"<span>Class {cls} - {lbl}</span></div>"
            )
        legend_html += '</div>'

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>THERMATO Report</title>
<style>
  body{{font-family:'Segoe UI',sans-serif;margin:0;background:#f4f6f9;color:#333}}
  .wrap{{max-width:960px;margin:30px auto;background:#fff;
         border-radius:12px;box-shadow:0 4px 24px rgba(0,0,0,.12);overflow:hidden}}
  .hero{{background:linear-gradient(135deg,#d63384,#6f42c1);color:#fff;padding:32px 40px}}
  .hero h1{{margin:0;font-size:2em}}
  .hero p{{margin:6px 0 0;opacity:.85}}
  .badge{{background:rgba(255,255,255,.2);padding:4px 12px;border-radius:20px;
          font-size:.8em;display:inline-block;margin-top:8px}}
  .body{{padding:32px 40px}}
  h2{{color:#6f42c1;border-left:4px solid #d63384;padding-left:12px;margin-top:36px}}
  h4{{color:#495057;margin-top:16px}}
  table{{width:100%;border-collapse:collapse;margin:12px 0;font-size:.9em}}
  th{{background:#6f42c1;color:#fff;padding:10px 12px;text-align:left}}
  td{{padding:8px 12px;border-bottom:1px solid #e9ecef}}
  tr:nth-child(even) td{{background:#f8f9fa}}
  .kpi{{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:20px 0}}
  .kpi-card{{background:#f8f9fa;border-radius:8px;padding:16px;text-align:center;
             border-top:3px solid #6f42c1}}
  .kpi-val{{font-size:1.7em;font-weight:700;color:#6f42c1}}
  .kpi-lbl{{font-size:.8em;color:#666;margin-top:4px}}
  .alert{{padding:14px 18px;margin:16px 0;border-radius:6px}}
  .alert.danger{{background:#f8d7da;border:1px solid #f5c2c7;color:#842029}}
  .alert.warning{{background:#fff3cd;border:1px solid #ffecb5;color:#856404}}
  .formula{{background:#f1f3f5;border-radius:6px;padding:14px 18px;
            font-family:monospace;font-size:1.1em;font-weight:600;
            text-align:center;margin:16px 0}}
  .code{{background:#f1f3f5;border-radius:6px;padding:14px 18px;
         font-family:monospace;font-size:.85em;line-height:1.6}}
  .footer{{background:#f8f9fa;padding:18px 40px;font-size:.82em;
           color:#6c757d;text-align:center;border-top:1px solid #e9ecef}}
</style>
</head>
<body>
<div class="wrap">
  <div class="hero">
    <h1>THERMATO Heat Risk Report</h1>
    <div class="badge">Single-folder output · PAL color table · Auto-resampling</div>
    <p>Generated: {ts} &nbsp;|&nbsp;
       Grid: {geo['shape'][0]:,}x{geo['shape'][1]:,} px &nbsp;|&nbsp;
       Res: {abs(gt[1]):.4f}x{abs(gt[5]):.4f}</p>
  </div>
  <div class="body">

    <div class="kpi">
      <div class="kpi-card"><div class="kpi-val">{r_mean:.2f}</div>
        <div class="kpi-lbl">Mean Risk Score</div></div>
      <div class="kpi-card"><div class="kpi-val">{r_min:.2f}-{r_max:.2f}</div>
        <div class="kpi-lbl">Score Range</div></div>
      <div class="kpi-card"><div class="kpi-val">{hr_count:,}</div>
        <div class="kpi-lbl">Very High Risk Pixels</div></div>
      <div class="kpi-card"><div class="kpi-val">{hr_pct:.1f}%</div>
        <div class="kpi-lbl">of Area (Class {max_cls})</div></div>
    </div>

    {alert_html}

    <h2>Risk Formula</h2>
    <div class="formula">Risk = {expr}</div>
    <table style="font-size:.9em">
      <tr><th>Component</th><th>Weight</th><th>Role</th></tr>
      <tr><td>LST</td><td>{weights['lst']:.1%}</td><td>Primary heat hazard</td></tr>
      <tr><td>NDBI</td><td>{weights['ndbi']:.1%}</td><td>Urban sensitivity</td></tr>
      <tr><td>NDVI</td><td>{weights['ndvi']:.1%}</td><td>Cooling capacity</td></tr>
      <tr><td>POP</td><td>{weights['pop']:.1%}</td><td>Human exposure</td></tr>
    </table>

    {classify_html}

    <h2>Auto-Resampling</h2>
    {resample_html}

    <h2>Input Statistics (Post-Resampling)</h2>
    <table>
      <tr><th>Layer</th><th>Min</th><th>Max</th><th>Mean</th><th>Std Dev</th><th>Coverage</th></tr>
      {stat_rows}
    </table>

    <h2>Classification Rules</h2>
    {rules_html}

    <h2>Risk Distribution</h2>
    {legend_html}
    <table>
      <tr><th>Class</th><th>Label</th><th>Pixels</th><th>%</th><th>Bar</th></tr>
      {cls_rows}
    </table>

    <h2>Output Files</h2>
    <table>
      <tr><th>Sub-folder</th><th>File</th><th>Description</th></tr>
      <tr><td>rasters/</td><td>risk_continuous.tif</td>
          <td>Float32, weighted score 1.0-5.0</td></tr>
      <tr><td>rasters/</td><td>risk_classified.tif</td>
          <td>Byte, classes 1-5 with embedded PAL color table</td></tr>
      <tr><td>vector/</td><td>risk_classified.gpkg</td>
          <td>Polygon with risk_class, risk_label, risk_color, area_m2, area_ha</td></tr>
      <tr><td>report/</td><td>report.html</td><td>This report</td></tr>
      <tr><td>report/</td><td>high_risk_coords.csv</td>
          <td>Class 5 pixel coordinates</td></tr>
      <tr><td>report/</td><td>summary.txt</td><td>Quick statistics</td></tr>
      <tr><td>report/</td><td>classification_rules.txt</td>
          <td>Applied classification rules</td></tr>
      <tr><td>report/</td><td>resampling_log.txt</td>
          <td>Resampling operations log</td></tr>
    </table>

  </div>
  <div class="footer">
    THERMATO &nbsp;·&nbsp;
    Hifzhan, Titus, Prasasta, Rayyan, Rafi &nbsp;·&nbsp;
    ITB 2026
  </div>
</div>
</body>
</html>"""
    def _build_csv_coords(self, risk_cls, risk_cont, geo, max_cls):
        lines = ['Priority,Row,Col,Risk_Score,Longitude,Latitude,Category']
        hr_rows, hr_cols = np.where(risk_cls == max_cls)
        
        if len(hr_rows) == 0:
            lines.append(f'# No Class {max_cls} (Highest Risk) pixels found')
            return '\n'.join(lines)
            
        hr_vals = risk_cont[hr_rows, hr_cols]
        sort_idx = np.argsort(hr_vals)[::-1]
        gt = geo['gt']
        for rank, idx in enumerate(sort_idx, 1):
            r, c = int(hr_rows[idx]), int(hr_cols[idx])
            val = float(hr_vals[idx])
            lon = gt[0] + c * gt[1]
            lat = gt[3] + r * gt[5]
            cat = 'CRITICAL' if val >= 4.8 else 'URGENT' if val >= 4.5 else 'HIGH'
            lines.append(f'{rank},{r},{c},{val:.4f},{lon:.6f},{lat:.6f},{cat}')
        return '\n'.join(lines)

    def _build_summary_text(self, input_stats, weights, expr, class_stats, risk_cont,
                            all_cls_vals, actual_hex_colors):
        vr          = risk_cont[~np.isnan(risk_cont)]
        total_valid = sum(class_stats.values())
        max_cls     = max(all_cls_vals)
        hr_count    = class_stats.get(max_cls, 0)
        pct_hr      = 100 * hr_count / total_valid if total_valid else 0
        n_cls       = len(all_cls_vals)

        lines = [
            'THERMATO - Heat Risk Analysis Summary',
            f'Generated: {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}',
            '',
            '=== RISK STATISTICS ===',
            f'Mean: {float(np.mean(vr)):.3f}  Std: {float(np.std(vr)):.3f}',
            f'Min:  {float(np.min(vr)):.3f}  Max: {float(np.max(vr)):.3f}',
            f'Total valid pixels: {len(vr):,}',
            '',
            '=== FORMULA ===',
            expr,
            '',
            '=== WEIGHTS ===',
        ]
        for k, w in weights.items():
            lines.append(f'  {k.upper()}: {w:.1%}')

        lines += ['', '=== CLASS DISTRIBUTION ===']
        for cls in all_cls_vals:
            cnt = class_stats.get(cls, 0)
            pct = 100 * cnt / total_valid if total_valid else 0
            pos = all_cls_vals.index(cls) + 1
            ratio = pos / n_cls
            if ratio <= 0.2:   lbl = 'Very Low'
            elif ratio <= 0.4: lbl = 'Low'
            elif ratio <= 0.6: lbl = 'Moderate'
            elif ratio <= 0.8: lbl = 'High'
            else:              lbl = 'Very High'
            lines.append(f'  Class {cls} ({lbl}): {cnt:,} px ({pct:.1f}%)')

        lines += ['', '=== INPUT COVERAGE ===']
        for k, s in input_stats.items():
            lines.append(
                f'  {k.upper()}: {s["coverage"]:.1f}% coverage, '
                f'range [{s["min"]:.3f}, {s["max"]:.3f}]'
            )

        lines += [
            '', '=== HIGH RISK ALERT ===',
            f'Highest Risk (Class {max_cls}): {hr_count:,} px ({pct_hr:.1f}%)',
            ('WARNING: >20% Very High Risk - immediate action recommended'
             if pct_hr > 20 else
             'CAUTION: >10% Very High Risk - consider mitigation'
             if pct_hr > 10 else
             'High risk areas are within manageable levels'),
        ]
        return '\n'.join(lines)


    def _build_rules_text(self, rules):
        desc = {
            'lst':  'LST (degrees C) - Heat hazard: higher temp = higher risk',
            'ndbi': 'NDBI - Urban sensitivity: higher built-up = higher risk',
            'ndvi': 'NDVI - Cooling capacity: higher vegetation = LOWER risk (INVERSE)',
            'pop':  'POP (people/km2) - Exposure: higher density = more people at risk',
        }
        lines = [
            'THERMATO - Classification Rules',
            f'Generated: {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}',
            '',
        ]
        for key, rl in rules.items():
            lines += [
                '=' * 60,
                f'{key.upper()} CLASSIFICATION',
                '=' * 60,
                desc[key], '',
            ]
            for i, (mn, mx, sc) in enumerate(rl, 1):
                mns = '-inf' if mn == float('-inf') else f'{mn:.2f}'
                mxs = '+inf' if mx == float('inf')  else f'{mx:.2f}'
                lines.append(f'  Rule {i}: [{mns}, {mxs}) -> Score {sc:.1f}')
            lines.append('')
        lines += [
            '=' * 60,
            'NOTES',
            '=' * 60,
            '- Intervals: left-inclusive, right-exclusive [min, max)',
            '- NDVI is inverse: high vegetation = low risk score',
            '- All components verified for score-range consistency',
            '- Rasters auto-resampled to LST reference grid',
        ]
        return '\n'.join(lines)

    # ================================================================
    # Cleanup
    # ================================================================
    def _cleanup_temp_files(self, resampled_paths, feedback):
        import shutil
        for name, path in resampled_paths.items():
            if name != 'lst' and os.path.exists(path):
                temp_dir = os.path.dirname(path)
                if 'thermato_' in temp_dir:
                    try:
                        shutil.rmtree(temp_dir)
                        feedback.pushInfo(
                            f'  Temp cleaned: {os.path.basename(temp_dir)}'
                        )
                        break
                    except Exception:
                        pass
