# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Thermato
                                 A QGIS plugin
 This plugin analyzes the correlation between heat exposure risk, land surface
 characteristics, and socio-economic vulnerability, and provides automated
 spatial estimation of urban heat risk patterns.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-12-10
        copyright            : (C) 2026 by Prof.Dr. Albertus Deliar, S.T., M.T., Prof. Ir. Ketut Wikantika, M.Eng, Ph.D., 
                               Dr. Alfita Puspa Handayani, S.T., M.T., Hifzhan Zhafir Faza, M. Titus Gideon,
                               Prasasta Adhitya Gunawan, Muhammad Ar Rayyan Ramadhani, Rafi Dwi Nugroho
        email                : albertus.deliar@gmail.com
 ***************************************************************************/
"""
__author__    = ('Prof.Dr. Albertus Deliar, S.T., M.T., Prof. Ir. Ketut Wikantika, M.Eng, Ph.D., '
                'Dr. Alfita Puspa Handayani, S.T., M.T., Hifzhan Zhafir Faza, M. Titus Gideon,'
                'Prasasta Adhitya Gunawan, Muhammad Ar Rayyan R., Rafi Dwi Nugroho')
__date__      = '2026-05-19'
__copyright__ = ('(C) 2026 by Prof.Dr. Albertus Deliar, S.T., M.T., Prof. Ir. Ketut Wikantika, M.Eng, Ph.D.,'
                'Dr. Alfita Puspa Handayani, S.T., M.T., Hifzhan Zhafir Faza, M. Titus Gideon, '
                'Prasasta Adhitya Gunawan, Muhammad Ar Rayyan Ramadhani, Rafi Dwi Nugroho')

from qgis.core import QgsProcessingProvider
from .thermato_algorithm import ThermatoAlgorithm
from qgis.PyQt.QtGui import QIcon
import os

print("ThermatoProvider loaded")
class ThermatoProvider(QgsProcessingProvider):

    def loadAlgorithms(self):
        self.addAlgorithm(ThermatoAlgorithm())

    def id(self):
        return 'THERMATO'

    def name(self):
        return 'THERMATO'

    def longName(self):
        return self.name()
    
    def icon(self):
        return QIcon(os.path.join(os.path.dirname(__file__), "icon.png"))
