# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Thermato
                                 A QGIS plugin
 This plugin analyzes the correlation between heat exposure risk, land surface
 characteristics, and socio-economic vulnerability, and provides automated
 spatial estimation of urban heat risk patterns.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-12-10
        copyright            : (C) 2026 by Prof.Dr. Albertus Deliar, S.T., M.T., Prof. Ir. Ketut Wikantika, M.Eng, Ph.D., 
                               Dr. Alfita Puspa Handayani, S.T., M.T., Hifzhan Zhafir Faza, M. Titus Gideon,
                               Prasasta Adhitya Gunawan, Muhammad Ar Rayyan Ramadhani, Rafi Dwi Nugroho
        email                : albertus.deliar@gmail.com
 ***************************************************************************/
"""
__author__    = ('Prof.Dr. Albertus Deliar, S.T., M.T., Prof. Ir. Ketut Wikantika, M.Eng, Ph.D., '
                'Dr. Alfita Puspa Handayani, S.T., M.T., Hifzhan Zhafir Faza, M. Titus Gideon,'
                'Prasasta Adhitya Gunawan, Muhammad Ar Rayyan R., Rafi Dwi Nugroho')
__date__      = '2026-'
__copyright__ = ('(C) 2026 by Prof.Dr. Albertus Deliar, S.T., M.T., Prof. Ir. Ketut Wikantika, M.Eng, Ph.D.,'
                'Dr. Alfita Puspa Handayani, S.T., M.T., Hifzhan Zhafir Faza, M. Titus Gideon, '
                'Prasasta Adhitya Gunawan, Muhammad Ar Rayyan Ramadhani, Rafi Dwi Nugroho')

import os
import processing

from qgis.core import QgsApplication
from qgis.PyQt.QtWidgets import QAction
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtCore import QCoreApplication

from .thermato_provider import ThermatoProvider


class TherMatoPlugin:

    def __init__(self, iface):
        self.iface = iface
        self.provider = None
        self.action = None

    def tr(self, message):
        return QCoreApplication.translate('THERMATO', message)

    def initGui(self):
        # Register Processing provider
        self.initProcessing()

        # Add menu entry
        self.action = QAction("THERMATO", self.iface.mainWindow())
        self.action.triggered.connect(self.run)
        self.iface.addPluginToMenu("&THERMATO", self.action)

    def initProcessing(self):
        self.provider = ThermatoProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def unload(self):
        if self.provider:
            QgsApplication.processingRegistry().removeProvider(self.provider)

        if self.action:
            self.iface.removePluginMenu("&THERMATO", self.action)

    def run(self):
        processing.execAlgorithmDialog('thermato:thermato')
