# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Thermato
                                 A QGIS plugin
 This plugin analyzes the correlation between heat exposure risk, land surface
 characteristics, and socio-economic vulnerability, and provides automated
 spatial estimation of heat risk patterns.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-12-10
        copyright            : (C) 2026 by Prof.Dr. Albertus Deliar, S.T., M.T., Prof. Ir. Ketut Wikantika, M.Eng, Ph.D., 
                               Dr. Alfita Puspa Handayani, S.T., M.T., Hifzhan Zhafir Faza, M. Titus Gideon,
                               Prasasta Adhitya Gunawan, Muhammad Ar Rayyan Ramadhani, Rafi Dwi Nugroho
        email                : albertus.deliar@gmail.com
 ***************************************************************************/
"""
__author__    = ('Prof.Dr. Albertus Deliar, S.T., M.T., Prof. Ir. Ketut Wikantika, M.Eng, Ph.D., '
                'Dr. Alfita Puspa Handayani, S.T., M.T., Hifzhan Zhafir Faza, M. Titus Gideon,'
                'Prasasta Adhitya Gunawan, Muhammad Ar Rayyan R., Rafi Dwi Nugroho')
__date__      = '2026-05-19'
__copyright__ = ('(C) 2026 by Prof.Dr. Albertus Deliar, S.T., M.T., Prof. Ir. Ketut Wikantika, M.Eng, Ph.D.,'
                'Dr. Alfita Puspa Handayani, S.T., M.T., Hifzhan Zhafir Faza, M. Titus Gideon, '
                'Prasasta Adhitya Gunawan, Muhammad Ar Rayyan Ramadhani, Rafi Dwi Nugroho')

import os
from qgis.PyQt import uic, QtWidgets
from qgis.PyQt.QtWidgets import QApplication, QFileDialog
from qgis.PyQt.QtCore import Qt
from qgis.core import QgsRasterLayer, QgsVectorLayer, QgsProject


FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), 'Ther_mato_dialog_base.ui')
)


class ThermatoDialog(QtWidgets.QDialog, FORM_CLASS):

    def __init__(self, parent=None):
        super(ThermatoDialog, self).__init__(parent)
        self.setupUi(self)

        # =========================================
        # LOAD EXISTING LAYERS
        # =========================================
        self.loadLayers()

        # =========================================
        # BROWSE BUTTON CONNECTIONS
        # =========================================
        self.btnNDBI.clicked.connect(lambda: self.browseRaster(self.cmbNDBI))
        self.btnNDVI.clicked.connect(lambda: self.browseRaster(self.cmbNDVI))
        self.btnLST.clicked.connect(lambda: self.browseRaster(self.cmbLST))
        self.btnPopulationDensity.clicked.connect(lambda: self.browseRaster(self.cmbPopulationDensity))
        self.btnBoundary.clicked.connect(self.browseVector)

        # =========================================
        # LOG BUTTONS
        # =========================================
        self.btnSaveLog.clicked.connect(self.saveLog)
        self.btnClearLog.clicked.connect(self.textEdit.clear)
        self.btnCopyLog.clicked.connect(
            lambda: QApplication.clipboard().setText(
                self.textEdit.toPlainText()
            )
        )

        # =========================================
        # COLLAPSE INFO PANEL (SPLITTER)
        # =========================================
        self.btnToggle.setCheckable(True)
        self.btnToggle.setArrowType(Qt.LeftArrow)
        self.btnToggle.toggled.connect(self.toggle_info_panel)

        
    # =====================================================
    # LOAD LAYERS FROM PROJECT
    # =====================================================
    def loadLayers(self):

        self.cmbNDBI.clear()
        self.cmbNDVI.clear()
        self.cmbLST.clear()
        self.cmbPopulationDensity.clear()
        self.cmbBoundary.clear()

        layers = QgsProject.instance().mapLayers().values()

        for layer in layers:

            if isinstance(layer, QgsRasterLayer):
                self.cmbNDBI.addItem(layer.name(), layer)
                self.cmbNDVI.addItem(layer.name(), layer)
                self.cmbLST.addItem(layer.name(), layer)
                self.cmbPopulationDensity.addItem(layer.name(), layer)
            
            elif isinstance(layer,QgsVectorLayer):
                self.cmbBoundary.addItem(layer.name(), layer)


    # =====================================================
    # BROWSE RASTER
    # =====================================================
    def browseRaster(self, comboBox):

        file_path, _ = QFileDialog.getOpenFileName(
            self,
            "Choose Raster File",
            "",
            "Raster Files (*.tif *.img *.asc)"
        )

        if file_path:
            layer = QgsRasterLayer(file_path, os.path.basename(file_path))
            if layer.isValid():
                QgsProject.instance().addMapLayer(layer)
                self.loadLayers()

    # =====================================================
    # BROWSE VECTOR
    # =====================================================
    def browseVector(self):

        file_path, _ = QFileDialog.getOpenFileName(
            self,
            "Choose Vector File",
            "",
            "Vector Files (*.shp *.gpkg *.geojson)"
        )

        if file_path:
            layer = QgsVectorLayer(file_path, os.path.basename(file_path), "ogr")
            if layer.isValid():
                QgsProject.instance().addMapLayer(layer)
                self.loadLayers()

    # =====================================================
    # SAVE LOG
    # =====================================================
    def saveLog(self):

        fileName, _ = QFileDialog.getSaveFileName(
            self,
            "Save Log",
            "",
            "Text Files (*.txt)"
        )

        if fileName:
            with open(fileName, "w", encoding="utf-8") as f:
                f.write(self.textEdit.toPlainText())

    # =====================================================
    # COLLAPSE INFO PANEL
    # =====================================================
    def toggle_info_panel(self, checked):

        if checked:
            self.splitter.setSizes([1, 0])
            self.btnToggle.setArrowType(Qt.RightArrow)
        else:
            self.splitter.setSizes([700, 300])
            self.btnToggle.setArrowType(Qt.LeftArrow)

    
